---
# Tasks to configure Nginx (site and proxy configs)

# Proxy confs must end in subdomain.conf to auto load

- name: "Copy proxy.conf"
  ansible.builtin.copy:
    src: "proxy.conf"
    dest: "{{ nginx__home }}/config/nginx/"
    mode: '0640'
  failed_when: false

- name: "Copy authelia-authrequest.conf"
  ansible.builtin.template:
    src: authelia-authrequest.conf.j2
    dest: "{{ nginx__home }}/config/nginx/authelia-authrequest.conf"
    owner: "{{ item.owner | default('root') }}" # First docker user (if docker role has run), otherwise default role, otherwise root
    group: "{{ item.group | default('root') }}"
    mode: '0640'
  when: nginx__add_authelia_config|bool

- name: "Copy authelia-location-basic.conf"
  ansible.builtin.template:
    src: authelia-location-basic.conf.j2
    dest: "{{ nginx__home }}/config/nginx/authelia-location-basic.conf"
    owner: "{{ item.owner | default('root') }}" # First docker user (if docker role has run), otherwise default role, otherwise root
    group: "{{ item.group | default('root') }}"
    mode: '0640'
  when: nginx__add_authelia_config|bool

- name: "Copy authelia-location.conf"
  ansible.builtin.template:
    src: authelia-location.conf.j2
    dest: "{{ nginx__home }}/config/nginx/authelia-location.conf"
    owner: "{{ item.owner | default('root') }}" # First docker user (if docker role has run), otherwise default role, otherwise root
    group: "{{ item.group | default('root') }}"
    mode: '0640'
  when: nginx__add_authelia_config|bool

- name: "Copy certs files for https sites {{ playbook_dir }}/files/nginx/certs/ to  keys folder"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/nginx/certs/{{ item.server_name }}.crt"
    dest: "{{ nginx__home }}/config/keys/{{ item.server_name }}.crt"
    owner: "root" 
    group: "root"
    mode: '0640'
  failed_when: false
  loop: "{{ nginx__proxy_confs_subdomain }}"
  notify: restart nginx
  when: nginx__proxy_confs_subdomain is defined and nginx__proxy_confs_subdomain|length>0 and item.listen_https is defined and item.listen_https|int > 0

- name: "Copy certs key files for https sites {{ playbook_dir }}/files/nginx/certs/ to  keys folder"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/nginx/certs/{{ item.server_name }}.key"
    dest: "{{ nginx__home }}/config/keys/{{ item.server_name }}.key"
    owner: "root" 
    group: "root"
    mode: '0640'
  failed_when: false
  loop: "{{ nginx__proxy_confs_subdomain }}"
  notify: restart nginx
  when: nginx__proxy_confs_subdomain is defined and nginx__proxy_confs_subdomain|length>0 and item.listen_https is defined and item.listen_https|int > 0

- name: Check if certificate key passwords are set
  ansible.builtin.template:
    src: key_passphrase.j2
    dest: "{{ nginx__home }}/config/keys/{{ item.server_name }}.passw"
    owner: "root" 
    group: "root"
    mode: '0640'
  loop: "{{ nginx__proxy_confs_subdomain }}"
  notify: restart nginx
  when: nginx__proxy_confs_subdomain is defined and nginx__proxy_confs_subdomain|length>0 and item.cert_key_passphrase is defined


- name: Generate proxy confs from nginx__proxy_confs_subdomain variable
  ansible.builtin.template:
    src: nginx_default_site_template.j2
    dest: "{{ nginx__home }}/config/nginx/site-confs/{{ item.server_name }}.conf"
    owner: "{{ item.owner | default('root') }}" 
    group: "{{ item.group | default('root') }}"
  loop: "{{ nginx__proxy_confs_subdomain }}"
  notify: restart nginx
  when: nginx__proxy_confs_subdomain is defined and nginx__proxy_confs_subdomain|length>0




- name: "Copy local site-confs if exists in {{ playbook_dir }}/files/nginx/site-confs/"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/nginx/site-confs/"
    dest: "{{ nginx__home }}/config/nginx/site-confs"
    mode: '0640'
  failed_when: false
  notify: restart nginx

- name: "Copy websites from ./files/nginx/sites/<subfolder> to /var/www (if exists)"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/nginx/sites/"
    dest: "/var/www"
    mode: '0740'
  failed_when: false
  notify: restart nginx
